---
all:
  children:
    spineleaf:
      children:
        dc1:
          hosts:
            DC1-P1-LF01:
              ansible_host: 10.1.100.131
        dc2:
          hosts:
            DC2-P1-LF01:
              ansible_host: 10.2.100.131
        dc3:
          hosts:
            DC3-P1-LF03:
              ansible_host: 10.3.100.161
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.nxos.nxos
        ansible_user: admin
        ansible_password: "{{ lookup('env', 'NXOS_PASSWORD') | default('admin_password', true) }}"
