core:
  raise_on_error: false

inventory:
  plugin: SimpleInventory
  options:
    host_file: "NXOS_AUTOMATION/inventory/hosts.yaml"
    group_file: "NXOS_AUTOMATION/inventory/groups.yaml"
    defaults_file: "NXOS_AUTOMATION/inventory/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 15

timeouts:
  socket_connect: 10
  operation: 20
  retries: 2
