# Demo-only Nornir inventory for a 2-spine / 8-leaf NX-OS fabric.
spine01:
  hostname: 192.0.2.11
  platform: nxos
  groups: [spine]
  data: { env: spineleaf, role: spine, fabric_id: SPN01 }

spine02:
  hostname: 192.0.2.12
  platform: nxos
  groups: [spine]
  data: { env: spineleaf, role: spine, fabric_id: SPN02 }

leaf01:
  hostname: 192.0.2.21
  platform: nxos
  groups: [leaf]
  data: { env: spineleaf, role: leaf, fabric_id: LEF01 }

leaf02:
  hostname: 192.0.2.22
  platform: nxos
  groups: [leaf]
  data: { env: spineleaf, role: leaf, fabric_id: LEF02 }

leaf03:
  hostname: 192.0.2.23
  platform: nxos
  groups: [leaf]
  data: { env: spineleaf, role: leaf, fabric_id: LEF03 }

leaf04:
  hostname: 192.0.2.24
  platform: nxos
  groups: [leaf]
  data: { env: spineleaf, role: leaf, fabric_id: LEF04 }

leaf05:
  hostname: 192.0.2.25
  platform: nxos
  groups: [leaf]
  data: { env: spineleaf, role: leaf, fabric_id: LEF05 }

leaf06:
  hostname: 192.0.2.26
  platform: nxos
  groups: [leaf]
  data: { env: spineleaf, role: leaf, fabric_id: LEF06 }

leaf07:
  hostname: 192.0.2.27
  platform: nxos
  groups: [leaf]
  data: { env: spineleaf, role: leaf, fabric_id: LEF07 }

leaf08:
  hostname: 192.0.2.28
  platform: nxos
  groups: [leaf]
  data: { env: spineleaf, role: leaf, fabric_id: LEF08 }
