DC1-P1-SS01:
  hostname: 192.0.2.11
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SS01
    border_gateway: false
DC1-P1-SS02:
  hostname: 192.0.2.12
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SS02
    border_gateway: false
DC1-P1-SP01:
  hostname: 192.0.2.21
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SP01
    border_gateway: false
DC1-P1-SP02:
  hostname: 192.0.2.22
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SP02
    border_gateway: false
DC1-P1-SP03:
  hostname: 192.0.2.23
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SP03
    border_gateway: false
DC1-P1-SP04:
  hostname: 192.0.2.24
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SP04
    border_gateway: false
DC1-P1-LF01:
  hostname: 192.0.2.31
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF01
    border_gateway: false
DC1-P1-LF02:
  hostname: 192.0.2.32
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF02
    border_gateway: false
DC1-P1-LF03:
  hostname: 192.0.2.33
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF03
    border_gateway: false
DC1-P1-LF04:
  hostname: 192.0.2.34
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF04
    border_gateway: false
DC1-P1-LF05:
  hostname: 192.0.2.35
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF05
    border_gateway: false
DC1-P1-LF06:
  hostname: 192.0.2.36
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF06
    border_gateway: false
DC1-P1-LF07:
  hostname: 192.0.2.37
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF07
    border_gateway: true
DC1-P1-LF08:
  hostname: 192.0.2.38
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF08
    border_gateway: true
DC1-P2-SS01:
  hostname: 192.0.2.111
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SS01
    border_gateway: false
DC1-P2-SS02:
  hostname: 192.0.2.112
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SS02
    border_gateway: false
DC1-P2-SP01:
  hostname: 192.0.2.121
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SP01
    border_gateway: false
DC1-P2-SP02:
  hostname: 192.0.2.122
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SP02
    border_gateway: false
DC1-P2-SP03:
  hostname: 192.0.2.123
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SP03
    border_gateway: false
DC1-P2-SP04:
  hostname: 192.0.2.124
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SP04
    border_gateway: false
DC1-P2-LF01:
  hostname: 192.0.2.131
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF01
    border_gateway: false
DC1-P2-LF02:
  hostname: 192.0.2.132
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF02
    border_gateway: false
DC1-P2-LF03:
  hostname: 192.0.2.133
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF03
    border_gateway: false
DC1-P2-LF04:
  hostname: 192.0.2.134
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF04
    border_gateway: false
DC1-P2-LF05:
  hostname: 192.0.2.135
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF05
    border_gateway: false
DC1-P2-LF06:
  hostname: 192.0.2.136
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF06
    border_gateway: false
DC1-P2-LF07:
  hostname: 192.0.2.137
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF07
    border_gateway: true
DC1-P2-LF08:
  hostname: 192.0.2.138
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF08
    border_gateway: true
DC2-P1-SS01:
  hostname: 198.51.100.11
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SS01
    border_gateway: false
DC2-P1-SS02:
  hostname: 198.51.100.12
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SS02
    border_gateway: false
DC2-P1-SP01:
  hostname: 198.51.100.21
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SP01
    border_gateway: false
DC2-P1-SP02:
  hostname: 198.51.100.22
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SP02
    border_gateway: false
DC2-P1-SP03:
  hostname: 198.51.100.23
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SP03
    border_gateway: false
DC2-P1-SP04:
  hostname: 198.51.100.24
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SP04
    border_gateway: false
DC2-P1-LF01:
  hostname: 198.51.100.31
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF01
    border_gateway: false
DC2-P1-LF02:
  hostname: 198.51.100.32
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF02
    border_gateway: false
DC2-P1-LF03:
  hostname: 198.51.100.33
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF03
    border_gateway: false
DC2-P1-LF04:
  hostname: 198.51.100.34
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF04
    border_gateway: false
DC2-P1-LF05:
  hostname: 198.51.100.35
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF05
    border_gateway: false
DC2-P1-LF06:
  hostname: 198.51.100.36
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF06
    border_gateway: false
DC2-P1-LF07:
  hostname: 198.51.100.37
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF07
    border_gateway: true
DC2-P1-LF08:
  hostname: 198.51.100.38
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF08
    border_gateway: true
DC2-P2-SS01:
  hostname: 198.51.100.111
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SS01
    border_gateway: false
DC2-P2-SS02:
  hostname: 198.51.100.112
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SS02
    border_gateway: false
DC2-P2-SP01:
  hostname: 198.51.100.121
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SP01
    border_gateway: false
DC2-P2-SP02:
  hostname: 198.51.100.122
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SP02
    border_gateway: false
DC2-P2-SP03:
  hostname: 198.51.100.123
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SP03
    border_gateway: false
DC2-P2-SP04:
  hostname: 198.51.100.124
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SP04
    border_gateway: false
DC2-P2-LF01:
  hostname: 198.51.100.131
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF01
    border_gateway: false
DC2-P2-LF02:
  hostname: 198.51.100.132
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF02
    border_gateway: false
DC2-P2-LF03:
  hostname: 198.51.100.133
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF03
    border_gateway: false
DC2-P2-LF04:
  hostname: 198.51.100.134
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF04
    border_gateway: false
DC2-P2-LF05:
  hostname: 198.51.100.135
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF05
    border_gateway: false
DC2-P2-LF06:
  hostname: 198.51.100.136
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF06
    border_gateway: false
DC2-P2-LF07:
  hostname: 198.51.100.137
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF07
    border_gateway: true
DC2-P2-LF08:
  hostname: 198.51.100.138
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF08
    border_gateway: true
DC3-P1-SS01:
  hostname: 203.0.113.11
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SS01
    border_gateway: false
DC3-P1-SS02:
  hostname: 203.0.113.12
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SS02
    border_gateway: false
DC3-P1-SP01:
  hostname: 203.0.113.21
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SP01
    border_gateway: false
DC3-P1-SP02:
  hostname: 203.0.113.22
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SP02
    border_gateway: false
DC3-P1-SP03:
  hostname: 203.0.113.23
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SP03
    border_gateway: false
DC3-P1-SP04:
  hostname: 203.0.113.24
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SP04
    border_gateway: false
DC3-P1-LF01:
  hostname: 203.0.113.31
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF01
    border_gateway: false
DC3-P1-LF02:
  hostname: 203.0.113.32
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF02
    border_gateway: false
DC3-P1-LF03:
  hostname: 203.0.113.33
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF03
    border_gateway: false
DC3-P1-LF04:
  hostname: 203.0.113.34
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF04
    border_gateway: false
DC3-P1-LF05:
  hostname: 203.0.113.35
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF05
    border_gateway: false
DC3-P1-LF06:
  hostname: 203.0.113.36
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF06
    border_gateway: false
DC3-P1-LF07:
  hostname: 203.0.113.37
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF07
    border_gateway: true
DC3-P1-LF08:
  hostname: 203.0.113.38
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF08
    border_gateway: true
DC3-P2-SS01:
  hostname: 203.0.113.111
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SS01
    border_gateway: false
DC3-P2-SS02:
  hostname: 203.0.113.112
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SS02
    border_gateway: false
DC3-P2-SP01:
  hostname: 203.0.113.121
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SP01
    border_gateway: false
DC3-P2-SP02:
  hostname: 203.0.113.122
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SP02
    border_gateway: false
DC3-P2-SP03:
  hostname: 203.0.113.123
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SP03
    border_gateway: false
DC3-P2-SP04:
  hostname: 203.0.113.124
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SP04
    border_gateway: false
DC3-P2-LF01:
  hostname: 203.0.113.131
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF01
    border_gateway: false
DC3-P2-LF02:
  hostname: 203.0.113.132
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF02
    border_gateway: false
DC3-P2-LF03:
  hostname: 203.0.113.133
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF03
    border_gateway: false
DC3-P2-LF04:
  hostname: 203.0.113.134
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF04
    border_gateway: false
DC3-P2-LF05:
  hostname: 203.0.113.135
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF05
    border_gateway: false
DC3-P2-LF06:
  hostname: 203.0.113.136
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF06
    border_gateway: false
DC3-P2-LF07:
  hostname: 203.0.113.137
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF07
    border_gateway: true
DC3-P2-LF08:
  hostname: 203.0.113.138
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF08
    border_gateway: true
