DC1-P1-SS01:
  hostname: 10.1.0.11
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SS01
    border_gateway: false
DC1-P1-SS02:
  hostname: 10.1.0.12
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SS02
    border_gateway: false
DC1-P1-SP01:
  hostname: 10.1.0.21
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SP01
    border_gateway: false
DC1-P1-SP02:
  hostname: 10.1.0.22
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SP02
    border_gateway: false
DC1-P1-SP03:
  hostname: 10.1.0.23
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SP03
    border_gateway: false
DC1-P1-SP04:
  hostname: 10.1.0.24
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-SP04
    border_gateway: false
DC1-P1-LF01:
  hostname: 10.1.0.31
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF01
    border_gateway: false
DC1-P1-LF02:
  hostname: 10.1.0.32
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF02
    border_gateway: false
DC1-P1-LF03:
  hostname: 10.1.0.33
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF03
    border_gateway: false
DC1-P1-LF04:
  hostname: 10.1.0.34
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF04
    border_gateway: false
DC1-P1-LF05:
  hostname: 10.1.0.35
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF05
    border_gateway: false
DC1-P1-LF06:
  hostname: 10.1.0.36
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF06
    border_gateway: false
DC1-P1-LF07:
  hostname: 10.1.0.37
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF07
    border_gateway: true
DC1-P1-LF08:
  hostname: 10.1.0.38
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC1
    pod: pod1
    fabric_id: DC1-P1-LF08
    border_gateway: true
DC1-P2-SS01:
  hostname: 10.1.0.111
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SS01
    border_gateway: false
DC1-P2-SS02:
  hostname: 10.1.0.112
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SS02
    border_gateway: false
DC1-P2-SP01:
  hostname: 10.1.0.121
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SP01
    border_gateway: false
DC1-P2-SP02:
  hostname: 10.1.0.122
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SP02
    border_gateway: false
DC1-P2-SP03:
  hostname: 10.1.0.123
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SP03
    border_gateway: false
DC1-P2-SP04:
  hostname: 10.1.0.124
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-SP04
    border_gateway: false
DC1-P2-LF01:
  hostname: 10.1.0.131
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF01
    border_gateway: false
DC1-P2-LF02:
  hostname: 10.1.0.132
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF02
    border_gateway: false
DC1-P2-LF03:
  hostname: 10.1.0.133
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF03
    border_gateway: false
DC1-P2-LF04:
  hostname: 10.1.0.134
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF04
    border_gateway: false
DC1-P2-LF05:
  hostname: 10.1.0.135
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF05
    border_gateway: false
DC1-P2-LF06:
  hostname: 10.1.0.136
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF06
    border_gateway: false
DC1-P2-LF07:
  hostname: 10.1.0.137
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF07
    border_gateway: true
DC1-P2-LF08:
  hostname: 10.1.0.138
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC1
    pod: pod2
    fabric_id: DC1-P2-LF08
    border_gateway: true
DC2-P1-SS01:
  hostname: 10.2.0.11
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SS01
    border_gateway: false
DC2-P1-SS02:
  hostname: 10.2.0.12
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SS02
    border_gateway: false
DC2-P1-SP01:
  hostname: 10.2.0.21
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SP01
    border_gateway: false
DC2-P1-SP02:
  hostname: 10.2.0.22
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SP02
    border_gateway: false
DC2-P1-SP03:
  hostname: 10.2.0.23
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SP03
    border_gateway: false
DC2-P1-SP04:
  hostname: 10.2.0.24
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-SP04
    border_gateway: false
DC2-P1-LF01:
  hostname: 10.2.0.31
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF01
    border_gateway: false
DC2-P1-LF02:
  hostname: 10.2.0.32
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF02
    border_gateway: false
DC2-P1-LF03:
  hostname: 10.2.0.33
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF03
    border_gateway: false
DC2-P1-LF04:
  hostname: 10.2.0.34
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF04
    border_gateway: false
DC2-P1-LF05:
  hostname: 10.2.0.35
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF05
    border_gateway: false
DC2-P1-LF06:
  hostname: 10.2.0.36
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF06
    border_gateway: false
DC2-P1-LF07:
  hostname: 10.2.0.37
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF07
    border_gateway: true
DC2-P1-LF08:
  hostname: 10.2.0.38
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC2
    pod: pod1
    fabric_id: DC2-P1-LF08
    border_gateway: true
DC2-P2-SS01:
  hostname: 10.2.0.111
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SS01
    border_gateway: false
DC2-P2-SS02:
  hostname: 10.2.0.112
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SS02
    border_gateway: false
DC2-P2-SP01:
  hostname: 10.2.0.121
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SP01
    border_gateway: false
DC2-P2-SP02:
  hostname: 10.2.0.122
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SP02
    border_gateway: false
DC2-P2-SP03:
  hostname: 10.2.0.123
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SP03
    border_gateway: false
DC2-P2-SP04:
  hostname: 10.2.0.124
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-SP04
    border_gateway: false
DC2-P2-LF01:
  hostname: 10.2.0.131
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF01
    border_gateway: false
DC2-P2-LF02:
  hostname: 10.2.0.132
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF02
    border_gateway: false
DC2-P2-LF03:
  hostname: 10.2.0.133
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF03
    border_gateway: false
DC2-P2-LF04:
  hostname: 10.2.0.134
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF04
    border_gateway: false
DC2-P2-LF05:
  hostname: 10.2.0.135
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF05
    border_gateway: false
DC2-P2-LF06:
  hostname: 10.2.0.136
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF06
    border_gateway: false
DC2-P2-LF07:
  hostname: 10.2.0.137
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF07
    border_gateway: true
DC2-P2-LF08:
  hostname: 10.2.0.138
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC2
    pod: pod2
    fabric_id: DC2-P2-LF08
    border_gateway: true
DC3-P1-SS01:
  hostname: 10.3.0.11
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SS01
    border_gateway: false
DC3-P1-SS02:
  hostname: 10.3.0.12
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SS02
    border_gateway: false
DC3-P1-SP01:
  hostname: 10.3.0.21
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SP01
    border_gateway: false
DC3-P1-SP02:
  hostname: 10.3.0.22
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SP02
    border_gateway: false
DC3-P1-SP03:
  hostname: 10.3.0.23
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SP03
    border_gateway: false
DC3-P1-SP04:
  hostname: 10.3.0.24
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-SP04
    border_gateway: false
DC3-P1-LF01:
  hostname: 10.3.0.31
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF01
    border_gateway: false
DC3-P1-LF02:
  hostname: 10.3.0.32
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF02
    border_gateway: false
DC3-P1-LF03:
  hostname: 10.3.0.33
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF03
    border_gateway: false
DC3-P1-LF04:
  hostname: 10.3.0.34
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF04
    border_gateway: false
DC3-P1-LF05:
  hostname: 10.3.0.35
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF05
    border_gateway: false
DC3-P1-LF06:
  hostname: 10.3.0.36
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF06
    border_gateway: false
DC3-P1-LF07:
  hostname: 10.3.0.37
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF07
    border_gateway: true
DC3-P1-LF08:
  hostname: 10.3.0.38
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC3
    pod: pod1
    fabric_id: DC3-P1-LF08
    border_gateway: true
DC3-P2-SS01:
  hostname: 10.3.0.111
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SS01
    border_gateway: false
DC3-P2-SS02:
  hostname: 10.3.0.112
  platform: nxos
  groups:
  - super_spine
  data:
    env: spineleaf
    role: super_spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SS02
    border_gateway: false
DC3-P2-SP01:
  hostname: 10.3.0.121
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SP01
    border_gateway: false
DC3-P2-SP02:
  hostname: 10.3.0.122
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SP02
    border_gateway: false
DC3-P2-SP03:
  hostname: 10.3.0.123
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SP03
    border_gateway: false
DC3-P2-SP04:
  hostname: 10.3.0.124
  platform: nxos
  groups:
  - spine
  data:
    env: spineleaf
    role: spine
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-SP04
    border_gateway: false
DC3-P2-LF01:
  hostname: 10.3.0.131
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF01
    border_gateway: false
DC3-P2-LF02:
  hostname: 10.3.0.132
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF02
    border_gateway: false
DC3-P2-LF03:
  hostname: 10.3.0.133
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF03
    border_gateway: false
DC3-P2-LF04:
  hostname: 10.3.0.134
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF04
    border_gateway: false
DC3-P2-LF05:
  hostname: 10.3.0.135
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF05
    border_gateway: false
DC3-P2-LF06:
  hostname: 10.3.0.136
  platform: nxos
  groups:
  - leaf
  data:
    env: spineleaf
    role: leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF06
    border_gateway: false
DC3-P2-LF07:
  hostname: 10.3.0.137
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF07
    border_gateway: true
DC3-P2-LF08:
  hostname: 10.3.0.138
  platform: nxos
  groups:
  - border_leaf
  data:
    env: spineleaf
    role: border_leaf
    site: DC3
    pod: pod2
    fabric_id: DC3-P2-LF08
    border_gateway: true
